<?php
$config = array(
    'index/login'
    =>array(
        array('field'=>'usuario',   'label'=>'Usuario', 'rules'=>'required|numeric|xss_clean'),
		array('field'=>'clave',     'label'=>'Clave',   'rules'=>'required|xss_clean')),
    'index/solicitud'
    =>array(
        array('field'=>'dni',   	'label'=>'DNI', 				'rules'=>'required|numeric|xss_clean'),
        array('field'=>'correo',   	'label'=>'Correo',   			'rules'=>'required|xss_clean|valid_email|valid_emails'),
        array('field'=>'nivel',   	'label'=>'Nivel de trabajo',	'rules'=>'required|xss_clean'),
        array('field'=>'diresa',   	'label'=>'Nivel de registro',	'rules'=>'xss_clean|callback_validar_establec'),
        array('field'=>'redes', 	'label'=>'Red', 				'rules'=>'xss_clean'),
        array('field'=>'microred', 	'label'=>'Microred', 			'rules'=>'xss_clean'),
        array('field'=>'establec', 	'label'=>'Establecimiento', 	'rules'=>'xss_clean'),
        array('field'=>'nombres', 	'label'=>'Apellidos y nombres',	'rules'=>'xss_clean')),
    'usuarios/usuario'
    =>array(
        array('field'=>'paterno',   'label'=>'Apellido Paterno',	'rules'=>'required|xss_clean'),
        array('field'=>'materno',   'label'=>'Apellido Materno',	'rules'=>'required|xss_clean'),
        array('field'=>'nombres',   'label'=>'Nombres',				'rules'=>'required|xss_clean'),
        array('field'=>'dni',   	'label'=>'DNI',   				'rules'=>'required|numeric|xss_clean'),
        array('field'=>'correo',   	'label'=>'Correo',   			'rules'=>'required|xss_clean|valid_email|valid_emails'),
        array('field'=>'usuario',  	'label'=>'Usuario',   			'rules'=>'required|xss_clean'),
        array('field'=>'contrasena','label'=>'Contrase&ntilde;a',   'rules'=>'required|xss_clean'),
        array('field'=>'nivel',   	'label'=>'Nivel',   			'rules'=>'required|xss_clean'),
        array('field'=>'fecha_not',	'label'=>'fecha de notificaci&oacute;n', 'rules'=>'required|xss_clean|callback_validar_fecha'),
        array('field'=>'estado',   	'label'=>'Estado',   			'rules'=>'required|xss_clean')),
    'operadores/usuario'
    =>array(
        array('field'=>'codigo',  	'label'=>'Usuario',   			'rules'=>'required|xss_clean'),
        array('field'=>'clave',		'label'=>'Contrase&ntilde;a',   'rules'=>'required|xss_clean'),
        array('field'=>'nombres',   'label'=>'Nombres',				'rules'=>'required|xss_clean'),
        array('field'=>'dni',   	'label'=>'DNI',   				'rules'=>'required|numeric|xss_clean'),
        array('field'=>'correo',   	'label'=>'Correo',   			'rules'=>'required|xss_clean|valid_email|valid_emails'),
        array('field'=>'nivel',   	'label'=>'Nivel',   			'rules'=>'required|xss_clean'),
        array('field'=>'caduca',	'label'=>'fecha de caducidad', 	'rules'=>'required|xss_clean|callback_validar_fecha'),
        array('field'=>'estado',   	'label'=>'Estado',   			'rules'=>'required|xss_clean')),
    'sistema/microred'
    =>array(
        array('field'=>'diresa', 	'label'=>'Diresa',			'rules'=>'required|xss_clean'),
        array('field'=>'redes',   	'label'=>'Redes',  			'rules'=>'required|xss_clean'),
        array('field'=>'codigo',	'label'=>'C&oacute;digo',	'rules'=>'required|xss_clean'),
        array('field'=>'nombre',   	'label'=>'Nombre', 			'rules'=>'required|xss_clean')),
    'sistema/establecimiento'
    =>array(
        array('field'=>'diresa', 	'label'=>'Diresa',			'rules'=>'required|xss_clean'),
        array('field'=>'redes',   	'label'=>'Redes',  			'rules'=>'required|xss_clean'),
        array('field'=>'microred', 	'label'=>'Microred',  		'rules'=>'required|xss_clean'),
        array('field'=>'codigo',	'label'=>'C&oacute;digo',	'rules'=>'required|xss_clean'),
        array('field'=>'renaes',	'label'=>'Renaes',			'rules'=>'required|xss_clean'),
        array('field'=>'nombre',   	'label'=>'Nombre', 			'rules'=>'required|xss_clean'),
        array('field'=>'notifica', 	'label'=>'notifica', 		'rules'=>'required|xss_clean'),
        array('field'=>'tipo',   	'label'=>'tipo', 			'rules'=>'required|xss_clean'),
        array('field'=>'nivel',   	'label'=>'nivel', 			'rules'=>'required|xss_clean'),
        array('field'=>'categoria', 'label'=>'categoria', 		'rules'=>'required|xss_clean')),
    'notificacion/individual'
    =>array(
        array('field'=>'vigilancias', 	'label'=>'Vigilancias',								'rules'=>'required|xss_clean'),
        array('field'=>'diresa', 		'label'=>'Diresa', 									'rules'=>'required|xss_clean'),
        array('field'=>'redes', 		'label'=>'Red', 									'rules'=>'required|xss_clean'),
        array('field'=>'microred', 		'label'=>'Microred', 								'rules'=>'required|xss_clean'),
        array('field'=>'establec', 		'label'=>'Establecimiento', 						'rules'=>'required|xss_clean'),
        array('field'=>'departamento', 	'label'=>'Departamento', 							'rules'=>'xss_clean'),
        array('field'=>'provincia', 	'label'=>'Provincia',	 							'rules'=>'xss_clean'),
        array('field'=>'distrito', 		'label'=>'Distrito', 								'rules'=>'callback_validar_ubigeo|xss_clean'),
        array('field'=>'localidad', 	'label'=>'Localidad', 								'rules'=>'xss_clean'),
        array('field'=>'apepat', 		'label'=>'Ap. Paterno', 							'rules'=>'required|xss_clean'),
        array('field'=>'apemat', 		'label'=>'Ap. Materno', 							'rules'=>'required|xss_clean'),
        array('field'=>'nombres', 		'label'=>'Nombres', 								'rules'=>'required|xss_clean'),
        array('field'=>'dni', 			'label'=>'DNI',		 								'rules'=>'required|numeric|xss_clean'),
        array('field'=>'historia', 		'label'=>'Historia',		 						'rules'=>'xss_clean'),
        array('field'=>'sexo', 			'label'=>'Sexo',	 								'rules'=>'required|callback_validar_sexo|xss_clean'),
        array('field'=>'edad', 			'label'=>'Edad',	 								'rules'=>'required|numeric|callback_validar_edad|xss_clean'),
        array('field'=>'tipo', 			'label'=>'Tipo de edad',							'rules'=>'required|xss_clean'),
        array('field'=>'direccion', 	'label'=>'Direcci&oacute;n',						'rules'=>'required|xss_clean'),
        array('field'=>'zona', 			'label'=>'Procedencia',								'rules'=>'xss_clean'),
        array('field'=>'diagno', 		'label'=>'Diagn&oacute;stico',						'rules'=>'required|callback_validar_defuncion|xss_clean'),
        array('field'=>'tipoDx', 		'label'=>'Tipo de Diagn&oacute;stico',				'rules'=>'required|callback_validar_tipoDiag|xss_clean'),
        array('field'=>'fecha_def',		'label'=>'fecha de defunci&oacute;n', 				'rules'=>'xss_clean'),
        array('field'=>'fecha_ini',		'label'=>'fecha de inicio de s&iacute;ntomas', 		'rules'=>'required|callback_validar_fecha|callback_validar_fechaIni|xss_clean'),
        array('field'=>'ano_ini',		'label'=>'A&ntilde;o de inicio de s&iacute;ntomas', 'rules'=>'required|xss_clean'),
        array('field'=>'semana_ini',	'label'=>'Semana de inicio de s&iacute;ntomas', 	'rules'=>'required|xss_clean'),
        array('field'=>'fecha_not',		'label'=>'fecha de notificaci&oacute;n', 			'rules'=>'required|validar_fecha|callback_validar_fechaNot|xss_clean'),
        array('field'=>'fecha_hos',		'label'=>'fecha de Hospitalziaci&oacute;n', 		'rules'=>'callback_validar_fecha|callback_validar_fechaHos|xss_clean'),
        array('field'=>'fecha_def',		'label'=>'fecha de Defunci&oacute;n', 				'rules'=>'callback_validar_fecha|callback_validar_fechaDef|xss_clean'),
        array('field'=>'fecha_inv',		'label'=>'fecha de investigaci&oacute;n', 			'rules'=>'callback_validar_fecha|callback_validar_fechaInv|xss_clean'),
        array('field'=>'protegido',		'label'=>'Protegido',					 			'rules'=>'xss_clean'),
        array('field'=>'muestra',		'label'=>'Muestra', 								'rules'=>'xss_clean'),
        array('field'=>'etnias',		'label'=>'Etnia', 									'rules'=>'xss_clean'),
        array('field'=>'subetnias',		'label'=>'Sub-Etnia', 								'rules'=>'xss_clean'),
        array('field'=>'otro',			'label'=>'Otra Etnia', 								'rules'=>'xss_clean'),
        array('field'=>'ano_not',		'label'=>'A&ntilde;o de notificaci&oacute;n',		'rules'=>'required|xss_clean'),
        array('field'=>'semana_not',	'label'=>'Semana de notificaci&oacute;n', 			'rules'=>'required|xss_clean')),
    'edas/edas'
    =>array(
        array('field'=>'diresa', 		'label'=>'Diresa', 								'rules'=>'required|xss_clean'),
        array('field'=>'redes', 		'label'=>'Red', 								'rules'=>'required|xss_clean'),
        array('field'=>'microred', 		'label'=>'Microred', 							'rules'=>'required|xss_clean'),
        array('field'=>'establec', 		'label'=>'Establecimiento', 					'rules'=>'required|xss_clean'),
        array('field'=>'departamento', 	'label'=>'Departamento', 						'rules'=>'required|xss_clean'),
        array('field'=>'provincia', 	'label'=>'Provincia',	 						'rules'=>'required|xss_clean'),
        array('field'=>'distrito', 		'label'=>'Distrito', 							'rules'=>'required|callback_validar_ubigeo|xss_clean'),
        array('field'=>'etnias',		'label'=>'Etnia', 								'rules'=>'xss_clean'),
        array('field'=>'subetnias',		'label'=>'Sub-Etnia', 							'rules'=>'xss_clean'),
        array('field'=>'zona', 			'label'=>'Procedencia',							'rules'=>'xss_clean'),
        array('field'=>'otro',			'label'=>'Otra Etnia', 							'rules'=>'xss_clean'),
        array('field'=>'ano',			'label'=>'A&ntilde;o de notificaci&oacute;n',	'rules'=>'required|numeric|callback_validar_anio|xss_clean'),
        array('field'=>'semana',		'label'=>'Semana de notificaci&oacute;n', 		'rules'=>'required|numeric|callback_validar_semana|xss_clean'),
        array('field'=>'daa_c1',		'label'=>'DAA en < 1 a&ntilde;o',				'rules'=>'numeric|callback_validar_cantidad|xss_clean'),
        array('field'=>'daa_c1_4',		'label'=>'DAA en < 4 a&ntilde;os',				'rules'=>'numeric|xss_clean'),
        array('field'=>'daa_c5',		'label'=>'DAA en > 5 a&ntilde;os',				'rules'=>'numeric|xss_clean'),
        array('field'=>'daa_d1',		'label'=>'Def. por DAA en < 1 a&ntilde;o',		'rules'=>'numeric|callback_validar_daa_d1|xss_clean'),
        array('field'=>'daa_d1_4',		'label'=>'Def. por DAA en < 4 a&ntilde;os',		'rules'=>'numeric|callback_validar_daa_d1_4|xss_clean'),
        array('field'=>'daa_d5',		'label'=>'Def. por DAA  en > 5 a&ntilde;os',	'rules'=>'numeric|callback_validar_daa_d5|xss_clean'),
        array('field'=>'daa_h1',		'label'=>'Hosp. por DAA en < 1 a&ntilde;o',		'rules'=>'numeric|callback_validar_daa_h1|xss_clean'),
        array('field'=>'daa_h1_4',		'label'=>'Hosp. por DAA en < 4 a&ntilde;os',	'rules'=>'numeric|callback_validar_daa_h1_4|xss_clean'),
        array('field'=>'daa_h5',		'label'=>'Hosp. por DAA en > 5 a&ntilde;os',	'rules'=>'numeric|callback_validar_daa_h5|xss_clean'),
        array('field'=>'dis_c1',		'label'=>'DIS en < 1 a&ntilde;o',				'rules'=>'numeric|xss_clean'),
        array('field'=>'dis_c1_4',		'label'=>'DIS en < 4 a&ntilde;os',				'rules'=>'numeric|xss_clean'),
        array('field'=>'dis_c5',		'label'=>'DIS en > 5 a&ntilde;os',				'rules'=>'numeric|xss_clean'),
        array('field'=>'dis_d1',		'label'=>'Def. por DIS en < 1 a&ntilde;o',		'rules'=>'numeric|callback_validar_dis_d1|xss_clean'),
        array('field'=>'dis_d1_4',		'label'=>'Def. por DIS en < 4 a&ntilde;os',		'rules'=>'numeric|callback_validar_dis_d1_4|xss_clean'),
        array('field'=>'dis_d5',		'label'=>'Def. por DIS  en > 5 a&ntilde;os',	'rules'=>'numeric|callback_validar_dis_d5|xss_clean'),
        array('field'=>'dis_h1',		'label'=>'Hosp. por DIS en < 1 a&ntilde;o',		'rules'=>'numeric|callback_validar_dis_h1|xss_clean'),
        array('field'=>'dis_h1_4',		'label'=>'Hosp. por DIS en < 4 a&ntilde;os',	'rules'=>'numeric|callback_validar_dis_h1_4|xss_clean'),
        array('field'=>'dis_h5',		'label'=>'Hosp. por DIS en > 5 a&ntilde;os',	'rules'=>'numeric|callback_validar_dis_h5|xss_clean')),
    'iras/iras'
    =>array(
        array('field'=>'diresa', 		'label'=>'Diresa', 								'rules'=>'required|xss_clean'),
        array('field'=>'redes', 		'label'=>'Red', 								'rules'=>'required|xss_clean'),
        array('field'=>'microred', 		'label'=>'Microred', 							'rules'=>'required|xss_clean'),
        array('field'=>'establec', 		'label'=>'Establecimiento', 					'rules'=>'required|xss_clean'),
        array('field'=>'departamento', 	'label'=>'Departamento', 						'rules'=>'required|xss_clean'),
        array('field'=>'provincia', 	'label'=>'Provincia',	 						'rules'=>'required|xss_clean'),
        array('field'=>'distrito', 		'label'=>'Distrito', 							'rules'=>'required|callback_validar_ubigeo|xss_clean'),
        array('field'=>'etnias',		'label'=>'Etnia', 								'rules'=>'xss_clean'),
        array('field'=>'subetnias',		'label'=>'Sub-Etnia', 							'rules'=>'xss_clean'),
        array('field'=>'zona', 			'label'=>'Procedencia',							'rules'=>'xss_clean'),
        array('field'=>'otro',			'label'=>'Otra Etnia', 							'rules'=>'xss_clean'),
        array('field'=>'ano',			'label'=>'A&ntilde;o de notificaci&oacute;n',	'rules'=>'required|numeric|callback_validar_anio|xss_clean'),
        array('field'=>'semana',		'label'=>'Semana de notificaci&oacute;n', 		'rules'=>'required|numeric|callback_validar_semana|xss_clean'),
        array('field'=>'ira_m2',		'label'=>'IRA en < 2 meses',					'rules'=>'numeric|callback_validar_cantidad|xss_clean'),
        array('field'=>'ira_2_11',		'label'=>'IRA de 2 a 11 meses',					'rules'=>'numeric|xss_clean'),
        array('field'=>'ira_1_4a',		'label'=>'IRA de 1 a 4 a&ntilde;os',			'rules'=>'numeric|xss_clean'),
        array('field'=>'neu_2_11',		'label'=>'NEUM de 2 a 11 meses',				'rules'=>'numeric|xss_clean'),
        array('field'=>'neu_1_4a',		'label'=>'NEUM de 1 a 4 a&ntilde;os',			'rules'=>'numeric|xss_clean'),
        array('field'=>'ngr_m2',		'label'=>'NGR en < 2 meses',					'rules'=>'numeric|xss_clean'),
        array('field'=>'ngr_2_11',		'label'=>'NGR de 2 a 11 meses',					'rules'=>'numeric|xss_clean'),
        array('field'=>'ngr_1_4a',		'label'=>'NGR de 1 a 4 a&ntilde;os',			'rules'=>'numeric|xss_clean'),
        array('field'=>'hos_m2',		'label'=>'HOSP en < 2 meses',					'rules'=>'numeric|callback_validar_hos_m2|xss_clean'),
        array('field'=>'hos_2_11',		'label'=>'HOSP de 2 a 11 meses',				'rules'=>'numeric|callback_validar_hos_2_11|xss_clean'),
        array('field'=>'hos_1_4a',		'label'=>'HOSP de 1 a 4 a&ntilde;os',			'rules'=>'numeric|callback_validar_hos_1_4a|xss_clean'),
        array('field'=>'dih_m2',		'label'=>'DIH en < 2 meses',					'rules'=>'numeric|callback_validar_dih_m2|xss_clean'),
        array('field'=>'dih_2_11',		'label'=>'DIH de 2 a 11 meses',					'rules'=>'numeric|callback_validar_dih_2_11|xss_clean'),
        array('field'=>'dih_1_4a',		'label'=>'DIH de 1 a 4 a&ntilde;os',			'rules'=>'numeric|callback_validar_dih_1_4a|xss_clean'),
        array('field'=>'deh_m2',		'label'=>'DEH en < 2 meses',					'rules'=>'numeric|callback_validar_deh_m2|xss_clean'),
        array('field'=>'deh_2_11',		'label'=>'DEH de 2 a 11 meses',					'rules'=>'numeric|callback_validar_deh_2_11|xss_clean'),
        array('field'=>'deh_1_4a',		'label'=>'DEH de 1 a 4 a&ntilde;os',			'rules'=>'numeric|callback_validar_deh_1_4a|xss_clean'),
        array('field'=>'neu_5_9a',		'label'=>'NEUM de 5 a 9 a&ntilde;os',			'rules'=>'numeric|xss_clean'),
        array('field'=>'neu_10_19',		'label'=>'NEUM de 10 a 19 a&ntilde;os',			'rules'=>'numeric|xss_clean'),
        array('field'=>'neu_20_59',		'label'=>'NEUM de 20 a 59 a&ntilde;os',			'rules'=>'numeric|xss_clean'),
        array('field'=>'neu_60a',		'label'=>'NEUM 60 a&ntilde;os a m&aacute;s',	'rules'=>'numeric|xss_clean'),
        array('field'=>'hos_5_9a',		'label'=>'HOSP de 5 a 9 a&ntilde;os',			'rules'=>'numeric|callback_validar_hos_5_9a|xss_clean'),
        array('field'=>'hos_10_19',		'label'=>'HOSP de 10 a 19 a&ntilde;os',			'rules'=>'numeric|callback_validar_hos_10_19|xss_clean'),
        array('field'=>'hos_20_59',		'label'=>'HOSP de 20 a 59 a&ntilde;os',			'rules'=>'numeric|callback_validar_hos_20_59|xss_clean'),
        array('field'=>'hos_60a',		'label'=>'HOSP 60 a&ntilde;os a m&aacute;s',	'rules'=>'numeric|callback_validar_hos_60a|xss_clean'),
        array('field'=>'dih_5_9a',		'label'=>'DIH de 5 a 9 a&ntilde;os',			'rules'=>'numeric|callback_validar_dih_5_9a|xss_clean'),
        array('field'=>'dih_10_19',		'label'=>'DIH de 10 a 19 a&ntilde;os',			'rules'=>'numeric|callback_validar_dih_10_19|xss_clean'),
        array('field'=>'dih_20_59',		'label'=>'DIH de 20 a 59 a&ntilde;os',			'rules'=>'numeric|callback_validar_dih_20_59|xss_clean'),
        array('field'=>'dih_60a',		'label'=>'DIH 60 a&ntilde;os a m&aacute;s',		'rules'=>'numeric|callback_validar_dih_60a|xss_clean'),
        array('field'=>'deh_5_9a',		'label'=>'DEH de 5 a 9 a&ntilde;os',			'rules'=>'numeric|callback_validar_deh_5_9a|xss_clean'),
        array('field'=>'deh_10_19',		'label'=>'DEH de 10 a 19 a&ntilde;os',			'rules'=>'numeric|callback_validar_deh_10_19|xss_clean'),
        array('field'=>'deh_20_59',		'label'=>'DEH de 20 a 59 a&ntilde;os',			'rules'=>'numeric|callback_validar_deh_20_59|xss_clean'),
        array('field'=>'deh_60a',		'label'=>'DEH 60 a&ntilde;os a m&aacute;s',		'rules'=>'numeric|callback_validar_deh_60a|xss_clean'),
        array('field'=>'sob_2a',		'label'=>'SOB menor de 2 a&ntilde;os',			'rules'=>'numeric|xss_clean'),
        array('field'=>'sob_2_4a',		'label'=>'SOB de 2 a 4 a&ntilde;os',			'rules'=>'numeric|xss_clean')),
    'febriles/febriles'
    =>array(
        array('field'=>'diresa', 		'label'=>'Diresa', 								'rules'=>'required|xss_clean'),
        array('field'=>'redes', 		'label'=>'Red', 								'rules'=>'required|xss_clean'),
        array('field'=>'microred', 		'label'=>'Microred', 							'rules'=>'required|xss_clean'),
        array('field'=>'establec', 		'label'=>'Establecimiento', 					'rules'=>'required|xss_clean'),
        array('field'=>'departamento', 	'label'=>'Departamento', 						'rules'=>'required|xss_clean'),
        array('field'=>'provincia', 	'label'=>'Provincia',	 						'rules'=>'required|xss_clean'),
        array('field'=>'distrito', 		'label'=>'Distrito', 							'rules'=>'required|callback_validar_ubigeo|xss_clean'),
        array('field'=>'ano',			'label'=>'A&ntilde;o de notificaci&oacute;n',	'rules'=>'required|numeric|callback_validar_anio|xss_clean'),
        array('field'=>'semana',		'label'=>'Semana de notificaci&oacute;n', 		'rules'=>'required|numeric|callback_validar_semana|xss_clean'),
        array('field'=>'feb_m1',		'label'=>'FEB. en < 1 a&ntilde;o',				'rules'=>'numeric|callback_validar_cantidad|xss_clean'),
        array('field'=>'feb_1_4',		'label'=>'FEB de 1 a 4 a&ntilde;os',			'rules'=>'numeric|xss_clean'),
        array('field'=>'feb_5_9',		'label'=>'FEB de 5 a 9 a&ntilde;os',			'rules'=>'numeric|xss_clean'),
        array('field'=>'feb_10_19',		'label'=>'FEB de 10 a 19 a&ntilde;os',			'rules'=>'numeric|xss_clean'),
        array('field'=>'feb_20_59',		'label'=>'FEB de 230 a 59 a&ntilde;os',			'rules'=>'numeric|xss_clean'),
        array('field'=>'feb_m60',		'label'=>'FEB mayores de 60 a&ntilde;os',		'rules'=>'numeric|xss_clean'),
        array('field'=>'feb_tot',		'label'=>'Total de febriles',					'rules'=>'require|numeric|xss_clean'),
        array('field'=>'fecha_not',		'label'=>'Fecha de notificaci&oacute;n',		'rules'=>'require|callback_validar_fecha|xss_clean'),
        array('field'=>'fecha_ate',		'label'=>'Fecha de atenci&oacute;n',			'rules'=>'require|callback_validar_fecha|xss_clean'),
        array('field'=>'tot_aten',		'label'=>'Total de atenciones',					'rules'=>'require|numeric|xss_clean')),
    'exportar/exportar'
    =>array(
        array('field'=>'anoExport',   'label'=>'A&ntilde;o de exportaci&oacute;n', 'rules'=>'required|numeric|xss_clean'),
        array('field'=>'baseExport',   'label'=>'Base para exportaci&oacute;n', 'rules'=>'required|xss_clean')),
    'mapas/mapas'
    =>array(
        array('field'=>'opciones',   	'label'=>'Opciones', 			'rules'=>'required|xss_clean'),
        array('field'=>'enfermedad',   	'label'=>'Enfermedad', 			'rules'=>'required|xss_clean'),
        array('field'=>'anio',   		'label'=>'Año', 				'rules'=>'required|xss_clean'),
        array('field'=>'nivel',   		'label'=>'Nivel', 				'rules'=>'required|xss_clean'),
        array('field'=>'diagno',   		'label'=>'Diagn&oacute;stico', 	'rules'=>'required|xss_clean')),
    'graficos/graficos'
    =>array(
        array('field'=>'opciones',   	'label'=>'Opciones', 			'rules'=>'required|xss_clean'),
        array('field'=>'enfermedad',   	'label'=>'Enfermedad', 			'rules'=>'required|xss_clean'),
        array('field'=>'anio',   		'label'=>'Año', 				'rules'=>'required|xss_clean'),
        array('field'=>'nivel',   		'label'=>'Nivel', 				'rules'=>'required|xss_clean'),
        array('field'=>'diagno',   		'label'=>'Diagn&oacute;stico', 	'rules'=>'required|xss_clean')),
    'reportes/reportes'
    =>array(
        array('field'=>'anio',   	'label'=>'A&ntilde;o',		 	'rules'=>'required|xss_clean'),
		array('field'=>'semana', 	'label'=>'Semana', 				'rules'=>'required|xss_clean')),
    'reportes/indTiempo'
    =>array(
        array('field'=>'anio',   	'label'=>'A&ntilde;o',		 	'rules'=>'required|xss_clean'),
        array('field'=>'diagno',   	'label'=>'Diagn&oacute;stico', 	'rules'=>'required|xss_clean')),
    'reportes/repIndividual'
    =>array(
        array('field'=>'descrip1', 	'label'=>'Descripci&oacute;n',	'rules'=>'callback_validar_Descripcion|xss_clean'),
        array('field'=>'diagno',   	'label'=>'Diagn&oacute;stico', 	'rules'=>'required|xss_clean')),
    'reportes/repColetivo'
    =>array(
        array('field'=>'descrip1', 	'label'=>'Descripci&oacute;n',	'rules'=>'callback_validar_Descripcion|xss_clean')),
    'pnt/Notificar'
    =>array(
        array('field'=>'userfile',	'label'=>'Archivo',		'rules'=>'require|xss_clean'),
        array('field'=>'diresa',	'label'=>'Diresa',		'rules'=>'require|xss_clean'),
        array('field'=>'anio', 		'label'=>'A&ntilde;o',	'rules'=>'require|xss_clean'),
        array('field'=>'semana',	'label'=>'Semana', 		'rules'=>'required|xss_clean')),
    'index/olvido'
    =>array(
        array('field'=>'correo',   'label'=>'Correo', 'rules'=>'required|xss_clean|valid_email|valid_emails')),
    'modulos3/RegfichaNeum'
    =>array(
        array('field'=>'diresa', 		'label'=>'diresa',				'rules'=>'required|xss_clean'),
        array('field'=>'redes', 		'label'=>'redes',				'rules'=>'xss_clean'),
        array('field'=>'microred', 		'label'=>'microred',			'rules'=>'xss_clean'),
        array('field'=>'establec', 		'label'=>'Establecimiento',		'rules'=>'required|xss_clean'),
        array('field'=>'institucion', 	'label'=>'institucion',			'rules'=>'xss_clean'),
        array('field'=>'fecha_reg', 	'label'=>'fecha de registro',	'rules'=>'required|callback_validar_fecha|xss_clean'),
        array('field'=>'departamento', 	'label'=>'departamento',		'rules'=>'required|xss_clean'),
        array('field'=>'provincia', 	'label'=>'provincia',			'rules'=>'required|xss_clean'),
        array('field'=>'distrito', 		'label'=>'distrito',			'rules'=>'required|xss_clean'),
        array('field'=>'apepat', 		'label'=>'apellido paterno',	'rules'=>'required|xss_clean'),
        array('field'=>'apemat', 		'label'=>'apellido materno',	'rules'=>'required|xss_clean'),
        array('field'=>'nombres', 		'label'=>'nombre',				'rules'=>'required|xss_clean'),
        array('field'=>'sexo', 			'label'=>'sexo',				'rules'=>'required|xss_clean'),
        array('field'=>'direccion', 	'label'=>'direccion',			'rules'=>'required|xss_clean'),
        array('field'=>'zona', 			'label'=>'zona',				'rules'=>'required|xss_clean'),
        array('field'=>'fecha_nac', 	'label'=>'fecha de nacimiento',	'rules'=>'required|callback_validar_fecha|xss_clean'),
        array('field'=>'fecha_ini', 	'label'=>'fecha de inicio',		'rules'=>'required|callback_validar_fecha|xss_clean'),
        array('field'=>'fecha_def', 	'label'=>'fecha de defuncion',	'rules'=>'required|callback_validar_fecha|xss_clean'),
        array('field'=>'hora_def', 		'label'=>'hora de defuncion',	'rules'=>'required|xss_clean'),
        array('field'=>'departamento14_1', 	'label'=>'departamento',		'rules'=>'required|xss_clean'),
        array('field'=>'provincia14_1', 'label'=>'provincia',			'rules'=>'required|xss_clean'),
        array('field'=>'distrito14_1', 	'label'=>'distrito',			'rules'=>'required|xss_clean'),
        array('field'=>'lugar_def', 	'label'=>'lugar de defuncion',	'rules'=>'required|xss_clean'),
        array('field'=>'otro_def', 		'label'=>'lugar de defuncion',	'rules'=>'xss_clean'),
        array('field'=>'cuidador',	 	'label'=>'cuidador',			'rules'=>'required|xss_clean'),
        array('field'=>'cuida_otro',	'label'=>'cuidador',			'rules'=>'xss_clean'),
        array('field'=>'lugar_atencion','label'=>'lugar',				'rules'=>'required|xss_clean'),
        array('field'=>'otro_lugar',	'label'=>'lugar',				'rules'=>'xss_clean'),
        array('field'=>'fecha_ate', 	'label'=>'fecha de atencion',	'rules'=>'required|callback_validar_fecha|xss_clean'),
        array('field'=>'seguro', 		'label'=>'seguro',				'rules'=>'xss_clean'),
        array('field'=>'otro_seguro', 	'label'=>'seguro',				'rules'=>'xss_clean'),
        array('field'=>'programa', 		'label'=>'programa',			'rules'=>'xss_clean'),
        array('field'=>'otro_programa', 'label'=>'otro_programa',		'rules'=>'xss_clean'),
        array('field'=>'pentavalente', 	'label'=>'pentavalente',		'rules'=>'xss_clean'),
        array('field'=>'neumococo', 	'label'=>'neumococo',			'rules'=>'xss_clean'),
        array('field'=>'influenza', 	'label'=>'influenza',			'rules'=>'xss_clean'),
        array('field'=>'talla', 		'label'=>'talla',				'rules'=>'required|xss_clean'),
        array('field'=>'peso', 			'label'=>'peso',				'rules'=>'required|xss_clean'),
        array('field'=>'nutricion', 	'label'=>'nutricion',			'rules'=>'required|xss_clean'),
        array('field'=>'tipo', 			'label'=>'tipo',				'rules'=>'xss_clean'),
        array('field'=>'lactancia', 	'label'=>'lactancia exclusiva',	'rules'=>'required|xss_clean'),
        array('field'=>'otro_lactancia','label'=>'otra lactancia',		'rules'=>'xss_clean'),
        array('field'=>'dx1', 			'label'=>'diagnotico de ingreso', 'rules'=>'xss_clean'),
        array('field'=>'dx2', 			'label'=>'diagnotico de ingreso', 'rules'=>'xss_clean'),
        array('field'=>'dx3', 			'label'=>'diagnotico de ingreso', 'rules'=>'xss_clean'),
        array('field'=>'cbasica', 		'label'=>'basica', 				'rules'=>'xss_clean'),
        array('field'=>'cintermedia', 	'label'=>'intermedia', 			'rules'=>'xss_clean'),
        array('field'=>'cterminal', 	'label'=>'terminal', 			'rules'=>'xss_clean'),
        array('field'=>'cred', 			'label'=>'cred', 				'rules'=>'xss_clean'),
        array('field'=>'hospital', 		'label'=>'hospitalaria', 		'rules'=>'xss_clean'),
        array('field'=>'fecha_tra', 	'label'=>'fecha transferencia',	'rules'=>'callback_validar_fecha|xss_clean'),
        array('field'=>'hora_tra', 		'label'=>'fecha transferencia',	'rules'=>'xss_clean'),
        array('field'=>'fecha_eme', 	'label'=>'fecha emergencia',	'rules'=>'callback_validar_fecha|xss_clean'),
        array('field'=>'hora_eme', 		'label'=>'fecha emergencia',	'rules'=>'xss_clean'),
        array('field'=>'fecha_hos', 	'label'=>'fecha hospitalizacion',	'rules'=>'callback_validar_fecha|xss_clean'),
        array('field'=>'hora_hos', 		'label'=>'fecha hospitalizacion',	'rules'=>'xss_clean'),
        array('field'=>'gravedad_tran',	'label'=>'transferencia', 		'rules'=>'xss_clean'),
        array('field'=>'acepto_tran',	'label'=>'transferencia', 		'rules'=>'xss_clean')
		),
    'modulos2/congenita'
    =>array(
        array('field'=>'diresa', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'redes', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'microred', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'establec', 			'label'=>'',								'rules'=>'xss_clean'),
		),
    'modulos2/materna'
    =>array(
        array('field'=>'diresa', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'redes', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'microred', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'establec', 			'label'=>'',								'rules'=>'xss_clean'),
		),
    'modulos/RegfichaChik'
    =>array(
        array('field'=>'semana', 			'label'=>'semana epidemiol&oacute;gica',	'rules'=>'required|numeric|xss_clean'),
        array('field'=>'fecha_nac', 		'label'=>'fecha nacimiento',				'rules'=>'callback_validar_fecha|xss_clean'),
        array('field'=>'departamento', 		'label'=>'departamento',					'rules'=>'xss_clean'),
        array('field'=>'provincia', 		'label'=>'provincia',						'rules'=>'xss_clean'),
        array('field'=>'distrito', 			'label'=>'distrito',						'rules'=>'xss_clean'),
        array('field'=>'localidad', 		'label'=>'localidad',						'rules'=>'required|xss_clean'),
        array('field'=>'direccion', 		'label'=>'direcci&oacute;n',				'rules'=>'required|xss_clean'),
        array('field'=>'ocupacion', 		'label'=>'ocupacion',						'rules'=>'xss_clean'),
        array('field'=>'telefono', 			'label'=>'telefono',						'rules'=>'xss_clean'),
        array('field'=>'investigador',	 	'label'=>'investigador',					'rules'=>'required|xss_clean'),
        array('field'=>'cargo', 			'label'=>'cargo',							'rules'=>'required|xss_clean'),
        array('field'=>'telefonos', 		'label'=>'telefonos',						'rules'=>'required|xss_clean'),
        array('field'=>'correo',   			'label'=>'correo',   						'rules'=>'required|xss_clean|valid_email')),
    'modulos4/plaguicidas'
    =>array(
        array('field'=>'codigo', 			'label'=>'c&oacute;digo',					'rules'=>'required|xss_clean'),
        array('field'=>'diresa', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'redes', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'microred', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'e_salud', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'departamento1', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'provincia1', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'distrito1', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'localidad1', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'captado', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'notificacion', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'captado_otro', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'notifica_otro', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'lugar_nac', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'embarazada', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'instruccion', 		'label'=>'instruccion',						'rules'=>'required|xss_clean'),
        array('field'=>'seguro', 			'label'=>'seguro',							'rules'=>'required|xss_clean'),
        array('field'=>'seguro_otro', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'ocupacion', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'departamento', 		'label'=>'departamento',					'rules'=>'xss_clean'),
        array('field'=>'provincia', 		'label'=>'provincia',						'rules'=>'xss_clean'),
        array('field'=>'distrito', 			'label'=>'distrito',						'rules'=>'required|xss_clean'),
        array('field'=>'localidad', 		'label'=>'localidad',						'rules'=>'required|xss_clean'),
        array('field'=>'direccion', 		'label'=>'direcci&oacute;n',				'rules'=>'required|xss_clean'),
        array('field'=>'telefono', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'referencia', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'etnia',		 		'label'=>'etnia',							'rules'=>'required|xss_clean'),
        array('field'=>'etnia_otro', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'procedencia', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'hora', 				'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'meridiano', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'ocurrencia', 		'label'=>'ocurrencia',						'rules'=>'required|xss_clean'),
        array('field'=>'trabajo', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'ocurrencia_otro', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'departamento14_1', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'provincia14_1', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'distrito14_1', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'localidad14_1', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'direccion14_1', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'alimentos', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'producto',		 	'label'=>'producto',						'rules'=>'required|xss_clean'),
        array('field'=>'producto_otro', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'nombre', 			'label'=>'nombre',							'rules'=>'required|xss_clean'),
        array('field'=>'concentracion', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'presentacion', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'cantidad', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'obtencion', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'circunstancia', 	'label'=>'circunstancia',					'rules'=>'required|xss_clean'),
        array('field'=>'circunstancia_otro', 'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'produccion', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'almacenamiento', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'agricola', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'salud',		 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'mantenimiento', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'humano', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'domiciliario', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'veterinario', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'reentrada', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'proteccion', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'mezcla', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'transporte', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'otros', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'actividad_otro', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'manejo', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'tiempo', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'tiemopo_tipo', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'produccion', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'eoral',   			'label'=>'v&iacute;a de exposici&oacute;n', 'rules'=>'xss_clean|callback_validar_via'),
        array('field'=>'piel',		 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'mucosas', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'respiratoria', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'desconocida', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'sistemico', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'fecha_con',   		'label'=>'consulta', 						'rules'=>'required|xss_clean|callback_validar_fecha'),
        array('field'=>'fecha_int',   		'label'=>'intoxicaci&oacute;n',				'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'fecha_nac',   		'label'=>'nacimiento', 						'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'fecha_loc',   		'label'=>'fecha local', 					'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'fecha_est',   		'label'=>'fecha establecimiento', 			'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'fecha_dir',   		'label'=>'fecha DIRESA', 					'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'nauseas',   		'label'=>'cuadro cl&iacute;nico', 			'rules'=>'xss_clean|callback_validar_cuadro'),
        array('field'=>'vomitos', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'abdominal', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'incontinencia', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'cefalea', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'diarreas', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'miosis', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'sudoracion', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'temblor', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'cianosis', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'midriasis', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'mareos', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'bradicardia', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'conciencia', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'disnea', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'convulsiones', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'polipnea', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'rash', 				'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'sibilancias', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'inferiores', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'proximales', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'insuficiencia', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'otro_sintoma', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'sin_sintomas', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'sintoma_otro', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'tipo', 				'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'anteriores', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'veces', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'fecha_ant',   		'label'=>'', 								'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'lugar_ant', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'anterior_otro',		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'observaciones', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'causa_ant', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'causa_otro', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'laboratorio', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'muestra', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'tipo_mue', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'tipomue_otro', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'fecha_mue',   		'label'=>'', 								'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'fecha_env',   		'label'=>'', 								'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'fecha_rec',   		'label'=>'', 								'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'colinesterasa', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'colinesterasa_res', 'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'metodo', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'examen_otro', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'examen_cual', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'servicio', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'fecha_ocu',   		'label'=>'', 								'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'destino', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'fecha_hos',   		'label'=>'', 								'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'destino_serv', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'oral', 				'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'oral_dosis', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'parenteral', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'parenteral_dosis', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'antidoto', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'secuelas', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'evolucion', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'fecha_alt',   		'label'=>'', 								'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'causa', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'mostrar',	 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'diagnostico', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'diagnostico_otro', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'fecha_inv1',   		'label'=>'inicio de investigaci&oacute;n', 	'rules'=>'required|xss_clean|callback_validar_fecha'),
        array('field'=>'fecha_inv2',   		'label'=>'final de investigaci&oacute;n', 	'rules'=>'required|xss_clean|callback_validar_fecha'),
        array('field'=>'investigador',	 	'label'=>'investigador',					'rules'=>'required|xss_clean'),
        array('field'=>'profesion', 		'label'=>'profesi&oacute;n',				'rules'=>'required|xss_clean'),
        array('field'=>'celular', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'telefono', 			'label'=>'tel&eacute;fono',					'rules'=>'required|xss_clean')),
    'modulos4/brotes'
    =>array(
        array('field'=>'codigo', 			'label'=>'c&oacute;digo',					'rules'=>'required|xss_clean'),
        array('field'=>'fecha_loc',			'label'=>'',								'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'fecha_est',			'label'=>'',								'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'fecha_inv',			'label'=>'',								'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'fecha_dir',			'label'=>'',								'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'fecha_not',			'label'=>'',								'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'fecha_rep',			'label'=>'',								'rules'=>'xss_clean|callback_validar_fecha'),
        array('field'=>'diresa', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'redes', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'microred', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'e_salud', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'ubigeo', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'localidad', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'descripcion', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'indice', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'ubigeo_rep', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'localidad_rep', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'sustancia', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'concentracion', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'cantidad', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'procendia', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'expuestos', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'noexpuestos', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'tipo',		 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'poblacion', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'lugar', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'actividad', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'direccion', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'condicion1', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'condicion2', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'condicion3', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'condicion4', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'condicion5', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'condicion6', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'condicion7', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'condicion8', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'condicion:_otros', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acto1', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acto2', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acto3', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acto4', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acto5', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acto6', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acto7', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acto8', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acto9', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acto10', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acto_otros', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'busqueda', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'educacion', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'examenes', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'fichas', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'informe', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acciones1', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acciones2', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acciones3', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acciones4', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'acciones5', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'personas', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'instituciones', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'observaciones', 	'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'responsable', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'profesion', 		'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'cargo', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'telefono', 			'label'=>'',								'rules'=>'xss_clean'),
        array('field'=>'celular', 			'label'=>'',								'rules'=>'xss_clean')),
    'sistema/busqueda'
    =>array(
        array('field'=>'busqueda',  'label'=>'B&uacute;squeda', 'rules'=>'required|numeric|xss_clean')),
    'modulosmnp/RegfichaMnp'
    =>array(
        array('field'=>'diresa', 		'label'=>'diresa', 				'rules'=>'required|xss_clean'),
        array('field'=>'redes', 		'label'=>'Red', 				'rules'=>'required|xss_clean'),
        array('field'=>'microred', 		'label'=>'microred', 		    'rules'=>'required|xss_clean'),
        array('field'=>'establec', 		'label'=>'Establecimiento', 	'rules'=>'required|xss_clean'),
        array('field'=>'fecha_mte', 	'label'=>'fecha de muerte',	    'rules'=>'required|callback_validar_fecha|xss_clean'),
        array('field'=>'fecha_nac', 	'label'=>'nacimiento', 			'rules'=>'required|xss_clean|callback_validar_fecha'),
        array('field'=>'ano', 			'label'=>'ano',					'rules'=>'required|xss_clean'),
        array('field'=>'semana', 		'label'=>'semana',				'rules'=>'required|xss_clean'),
        array('field'=>'causa_bas', 	'label'=>'causa_bas',			'rules'=>'xss_clean'),
        array('field'=>'diagno', 		'label'=>'diagno',				'rules'=>'required|xss_clean'),
        array('field'=>'tipo_mte', 		'label'=>'tipo_mte',			'rules'=>'required|xss_clean'),
		array('field'=>'edadges', 		'label'=>'edadges',				'rules'=>'required|xss_clean'),
		array('field'=>'peso_nac', 		'label'=>'peso_nac',			'rules'=>'required|xss_clean'),
        array('field'=>'distrito14_1', 	'label'=>'distrito',			'rules'=>'required|xss_clean'),
        array('field'=>'apepat', 		'label'=>'apellido paterno',	'rules'=>'required|xss_clean'),
        array('field'=>'apemat', 		'label'=>'apellido materno',	'rules'=>'required|xss_clean'),
        array('field'=>'nombres', 		'label'=>'nombre',				'rules'=>'required|xss_clean'),
        array('field'=>'hora_nac', 		'label'=>'',					'rules'=>'required|xss_clean'),
        array('field'=>'hora_mte', 		'label'=>'',					'rules'=>'required|xss_clean'),		
        array('field'=>'responsabl', 	'label'=>'',					'rules'=>'xss_clean'),		
        array('field'=>'sexo', 			'label'=>'',					'rules'=>'required|xss_clean'),		
        array('field'=>'codcat', 		'label'=>'',					'rules'=>'xss_clean'),
        array('field'=>'estancia', 		'label'=>'',					'rules'=>'xss_clean'),
        array('field'=>'categoria',		'label'=>'',					'rules'=>'xss_clean'),
        array('field'=>'dni_madre',		'label'=>'',					'rules'=>'xss_clean'),
        array('field'=>'lugar_par',		'label'=>'',					'rules'=>'xss_clean'),
        array('field'=>'momento',		'label'=>'',					'rules'=>'required|xss_clean'),
        array('field'=>'lugar_mte',		'label'=>'',					'rules'=>'xss_clean'),
        array('field'=>'diasvid', 		'label'=>'dias de vida',		'rules'=>'xss_clean'),
        array('field'=>'ape_nom', 		'label'=>'ape_nom',				'rules'=>'required|xss_clean'))
         
);
?>